CREATE TABLE `city_showcase_videos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`cityName` varchar(255) NOT NULL,
	`stateName` varchar(100) NOT NULL,
	`videoLength` int NOT NULL DEFAULT 180,
	`introScript` text,
	`midScript1` text,
	`midScript2` text,
	`outroScript` text,
	`brollScript1` text,
	`brollScript2` text,
	`brollScript3` text,
	`cityData` text,
	`introVideoUrl` text,
	`midVideo1Url` text,
	`midVideo2Url` text,
	`outroVideoUrl` text,
	`brollVideo1Url` text,
	`brollVideo2Url` text,
	`brollVideo3Url` text,
	`finalVideoUrl` text,
	`thumbnailUrl` text,
	`status` enum('draft','generating_scripts','generating_avatar','generating_broll','compositing','completed','failed') NOT NULL DEFAULT 'draft',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `city_showcase_videos_id` PRIMARY KEY(`id`)
);
