CREATE TABLE `buyer_presentations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(500) NOT NULL,
	`buyerName` varchar(255),
	`buyerType` varchar(100),
	`priceRange` varchar(200),
	`targetAreas` text,
	`desiredBedrooms` varchar(20),
	`desiredBathrooms` varchar(20),
	`mustHaves` text,
	`niceToHaves` text,
	`timeline` varchar(200),
	`marketCity` varchar(255),
	`marketState` varchar(100),
	`marketOverview` text,
	`avgDaysOnMarket` varchar(50),
	`avgListPrice` varchar(100),
	`inventoryLevel` varchar(100),
	`financingNotes` text,
	`lenderName` varchar(255),
	`lenderContact` varchar(255),
	`agentName` varchar(255),
	`agentHeadshotUrl` text,
	`agentBio` text,
	`agentStats` text,
	`agentTestimonials` text,
	`processSteps` text,
	`buyerConcerns` text,
	`gammaId` varchar(255),
	`gammaUrl` text,
	`exportFormat` enum('pdf','pptx') DEFAULT 'pptx',
	`thumbnailUrl` text,
	`status` enum('draft','generating','completed','failed') NOT NULL DEFAULT 'draft',
	`inputData` text,
	`creditsCost` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `buyer_presentations_id` PRIMARY KEY(`id`)
);
