export default function FairHousing() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border">
        <div className="container mx-auto px-4 py-4">
          <a href="/landing" className="flex items-center gap-2">
            <img src="https://files.manuscdn.com/user_upload_by_module/session_file/310419663026756998/OIiAbFpfnRfWzAsg.png" alt="Amped Agent" className="h-8 object-contain" />
          </a>
        </div>
      </header>

      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Fair Housing Disclaimer</h1>
        <p className="text-sm text-muted-foreground mb-8">Last Updated: January 14, 2026</p>

        <div className="prose prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-bold mb-4">Equal Housing Opportunity</h2>
            <p>
              Amped Agent is committed to supporting fair housing practices and equal opportunity in real estate. All content generated by our Service should comply with fair housing laws and regulations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Fair Housing Act Compliance</h2>
            <p>
              The Fair Housing Act prohibits discrimination in housing based on:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Race or color</li>
              <li>National origin</li>
              <li>Religion</li>
              <li>Sex (including gender identity and sexual orientation)</li>
              <li>Familial status (including children under 18 living with parents or legal custodians, pregnant women, and people securing custody of children under 18)</li>
              <li>Disability</li>
            </ul>
            <p className="mt-4">
              Additionally, many states and localities have laws that provide additional protected classes beyond those listed in the federal Fair Housing Act.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Your Responsibility</h2>
            <p>
              As a real estate professional using Amped Agent, you are responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Reviewing all AI-generated content for compliance with fair housing laws</li>
              <li>Removing any language that could be discriminatory or suggest preference, limitation, or discrimination</li>
              <li>Ensuring property descriptions and marketing materials comply with fair housing requirements</li>
              <li>Understanding and following fair housing laws in your jurisdiction</li>
              <li>Consulting with your broker or legal counsel if you have questions about compliance</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Prohibited Content</h2>
            <p>
              Do not publish content that:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Indicates preference, limitation, or discrimination based on protected classes</li>
              <li>Uses words or phrases that suggest discrimination (e.g., "perfect for families," "adult community," "no children")</li>
              <li>Describes neighborhoods in ways that could imply racial, ethnic, or religious composition</li>
              <li>Targets or excludes specific groups of people</li>
              <li>Makes assumptions about who would or would not be interested in a property</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Best Practices</h2>
            <p>
              When creating real estate content:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Focus on property features, not potential buyers</li>
              <li>Describe neighborhoods objectively (e.g., proximity to schools, parks, shopping) without characterizing residents</li>
              <li>Use inclusive language that welcomes all potential buyers</li>
              <li>Avoid assumptions about family structure, lifestyle, or demographics</li>
              <li>When in doubt, consult fair housing guidelines or your broker</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">AI Content Limitations</h2>
            <p>
              While our AI is designed to avoid discriminatory language, it may occasionally generate content that requires review. Always:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Read all AI-generated content carefully before publishing</li>
              <li>Edit or remove any potentially problematic language</li>
              <li>Apply your professional judgment and knowledge of fair housing laws</li>
              <li>Report any concerning patterns to our support team</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Resources</h2>
            <p>
              For more information about fair housing compliance:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>U.S. Department of Housing and Urban Development (HUD): <a href="https://www.hud.gov/fairhousing" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">www.hud.gov/fairhousing</a></li>
              <li>National Association of REALTORS® Fair Housing Resources</li>
              <li>Your state real estate commission</li>
              <li>Your brokerage's compliance officer</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Disclaimer</h2>
            <p>
              This information is provided for educational purposes only and does not constitute legal advice. Amped Agent is not responsible for ensuring your compliance with fair housing laws. You should consult with your broker, legal counsel, or compliance officer for guidance on fair housing compliance.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Contact Us</h2>
            <p>
              If you have questions or concerns about fair housing compliance, please contact us at:
            </p>
            <p className="mt-2">
              Email: <a href="mailto:compliance@realtycontentagent.com" className="text-primary hover:underline">compliance@realtycontentagent.com</a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-border">
          <a href="/landing" className="text-primary hover:underline">
            ← Back to Home
          </a>
        </div>
      </div>
    </div>
  );
}
