export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  facebookAppId: process.env.FACEBOOK_APP_ID ?? "",
  facebookAppSecret: process.env.FACEBOOK_APP_SECRET ?? "",
  ghlWebhookSecret: process.env.GHL_WEBHOOK_SECRET ?? "",
  ghlAgencyApiKey: process.env.GHL_AGENCY_API_KEY ?? "",
  ghlAgencyId: process.env.GHL_AGENCY_ID ?? "",
  ghlCompanyId: process.env.GHL_COMPANY_ID ?? "",
  ghlLocationApiKey: process.env.GHL_LOCATION_API_KEY ?? "",
  rapidApiKey: process.env.RAPIDAPI_KEY ?? "",
  linkedinClientId: process.env.LINKEDIN_CLIENT_ID ?? "",
  linkedinClientSecret: process.env.LINKEDIN_CLIENT_SECRET ?? "",
  SHOTSTACK_API_KEY: process.env.SHOTSTACK_API_KEY ?? "",
  SHOTSTACK_HOST: process.env.SHOTSTACK_HOST ?? "https://api.shotstack.io/stage",
  LUMA_API_KEY: process.env.LUMA_API_KEY ?? "",
  RUNWAY_API_KEY: process.env.RUNWAY_API_KEY ?? "",
  ELEVENLABS_API_KEY: process.env.ELEVENLABS_API_KEY ?? "",
};
