/**
 * Seed hooks into database
 * Run with: node server/seeds/seed-hooks.mjs
 */

import { createConnection } from 'mysql2/promise';

const hookSeeds = [
  // BUYER HOOKS
  {
    category: "buyer",
    format: "video",
    hookText: "Stop scrolling if you're tired of losing bidding wars...",
    useCase: "For buyers frustrated with competitive markets",
    exampleExpansion: "Stop scrolling if you're tired of losing bidding wars... I'm about to share 3 strategies that helped my clients win in multiple-offer situations without overpaying.",
    isPremium: false,
  },
  {
    category: "buyer",
    format: "video",
    hookText: "First-time homebuyers: This mistake could cost you $50K+",
    useCase: "Warning hook for first-time buyers",
    exampleExpansion: "First-time homebuyers: This mistake could cost you $50K+. Most new buyers skip this one step in the inspection process, and it comes back to haunt them years later.",
    isPremium: false,
  },
  {
    category: "buyer",
    format: "video",
    hookText: "You don't need 20% down to buy a house. Here's what you actually need...",
    useCase: "Debunking common buyer myths",
    exampleExpansion: "You don't need 20% down to buy a house. Here's what you actually need... I'll break down 5 loan programs that require as little as 0-3% down.",
    isPremium: false,
  },
  {
    category: "buyer",
    format: "video",
    hookText: "POV: You just found your dream home but your agent says 'don't make an offer yet'",
    useCase: "Creating curiosity about the buying process",
    exampleExpansion: "POV: You just found your dream home but your agent says 'don't make an offer yet'. Here's why waiting 24 hours could save you thousands...",
    isPremium: true,
  },
  {
    category: "buyer",
    format: "video",
    hookText: "3 red flags to look for during a showing that most buyers miss",
    useCase: "Educational content for home tours",
    exampleExpansion: "3 red flags to look for during a showing that most buyers miss. Number 2 could indicate a $30K+ foundation issue.",
    isPremium: true,
  },
  {
    category: "buyer",
    format: "social",
    hookText: "Thinking about buying in [City]? Here's what $500K gets you right now:",
    useCase: "Market snapshot for buyers",
    exampleExpansion: "Thinking about buying in Austin? Here's what $500K gets you right now: 3 bed/2 bath in Mueller, 4 bed/2 bath in Pflugerville, or a downtown condo with skyline views.",
    isPremium: false,
  },
  {
    category: "buyer",
    format: "social",
    hookText: "Just closed on this beauty for $15K under asking. Want to know how?",
    useCase: "Success story to attract buyers",
    exampleExpansion: "Just closed on this beauty for $15K under asking. Want to know how? It all came down to timing and a strategic inspection negotiation. DM me for the full story.",
    isPremium: false,
  },
  {
    category: "buyer",
    format: "social",
    hookText: "Your rent just went up again? Let's talk about what you could own for the same monthly payment.",
    useCase: "Rent vs buy comparison",
    exampleExpansion: "Your rent just went up again? Let's talk about what you could own for the same monthly payment. Spoiler: It's probably more than you think.",
    isPremium: true,
  },
  {
    category: "buyer",
    format: "email",
    hookText: "I just got off the phone with a lender who shared something surprising about rates...",
    useCase: "Timely market update email",
    exampleExpansion: "I just got off the phone with a lender who shared something surprising about rates... If you've been waiting for the 'perfect time' to buy, this might be it.",
    isPremium: true,
  },
  {
    category: "buyer",
    format: "email",
    hookText: "Quick question: Are you still looking for a home in [Area]?",
    useCase: "Re-engagement email for past leads",
    exampleExpansion: "Quick question: Are you still looking for a home in North Austin? I have 3 new listings hitting the market this week that match your criteria perfectly.",
    isPremium: true,
  },
  {
    category: "buyer",
    format: "video",
    hookText: "This is why your offer keeps getting rejected (and how to fix it)",
    useCase: "Offer strategy advice",
    exampleExpansion: "This is why your offer keeps getting rejected (and how to fix it): You're making these 3 common mistakes that sellers hate. Let me show you what winning offers look like.",
    isPremium: true,
  },
  {
    category: "buyer",
    format: "video",
    hookText: "New construction vs resale: Which should you buy?",
    useCase: "Buyer decision framework",
    exampleExpansion: "New construction vs resale: Which should you buy? The answer isn't what most people think. Here are the pros and cons of each based on your situation.",
    isPremium: true,
  },
  {
    category: "buyer",
    format: "social",
    hookText: "Mortgage rates dropped this week. Here's what it means for your buying power:",
    useCase: "Rate update with action item",
    exampleExpansion: "Mortgage rates dropped this week. Here's what it means for your buying power: That $400K home you couldn't afford last month? You can now. Let's run the numbers.",
    isPremium: false,
  },
  {
    category: "buyer",
    format: "social",
    hookText: "Just helped a client buy their first home with $0 down. Here's how:",
    useCase: "Low down payment success story",
    exampleExpansion: "Just helped a client buy their first home with $0 down. Here's how: VA loan for veterans, USDA loan for rural areas, or grant programs for first-timers. Options exist!",
    isPremium: true,
  },
  {
    category: "buyer",
    format: "email",
    hookText: "I found 3 homes that match your criteria. Want to see them this weekend?",
    useCase: "Personalized listing alert",
    exampleExpansion: "I found 3 homes that match your criteria. Want to see them this weekend? All 3 are in your price range, have the features you wanted, and just hit the market. Let me know your availability.",
    isPremium: true,
  },
  {
    category: "buyer",
    format: "carousel",
    hookText: "10 Things First-Time Buyers Should Know Before Making an Offer",
    useCase: "Educational carousel for new buyers",
    exampleExpansion: "Slide 1: 10 Things First-Time Buyers Should Know. Slide 2: Pre-approval vs Pre-qualification. Slide 3: Earnest money explained... (continues for 10 slides)",
    isPremium: false,
  },
  {
    category: "buyer",
    format: "carousel",
    hookText: "Home Inspection Red Flags: What to Look For",
    useCase: "Inspection education",
    exampleExpansion: "Slide 1: Home Inspection Red Flags. Slide 2: Foundation cracks. Slide 3: Roof damage. Slide 4: Electrical issues... (continues with 10 red flags)",
    isPremium: false,
  },

  // SELLER HOOKS
  {
    category: "seller",
    format: "video",
    hookText: "Your neighbor just sold for $50K more than you expected. Here's why...",
    useCase: "Creating urgency for sellers",
    exampleExpansion: "Your neighbor just sold for $50K more than you expected. Here's why... The market in [Neighborhood] has shifted dramatically in the last 60 days.",
    isPremium: false,
  },
  {
    category: "seller",
    format: "video",
    hookText: "Stop! Don't list your home until you do these 3 things first.",
    useCase: "Pre-listing advice",
    exampleExpansion: "Stop! Don't list your home until you do these 3 things first. Number 2 takes 30 minutes but adds $10K+ to your sale price.",
    isPremium: false,
  },
  {
    category: "seller",
    format: "video",
    hookText: "I just walked through a $2M listing that won't sell. Want to know why?",
    useCase: "Common selling mistakes",
    exampleExpansion: "I just walked through a $2M listing that won't sell. Want to know why? It's making the same 3 mistakes I see in 80% of overpriced homes.",
    isPremium: false,
  },
  {
    category: "seller",
    format: "video",
    hookText: "Sellers: If your agent isn't doing THIS, you're leaving money on the table",
    useCase: "Differentiating your services",
    exampleExpansion: "Sellers: If your agent isn't doing THIS, you're leaving money on the table. This one marketing strategy increased my average sale price by 7%.",
    isPremium: true,
  },
  {
    category: "seller",
    format: "video",
    hookText: "POV: You listed with a discount broker to save on commission...",
    useCase: "Addressing discount brokers",
    exampleExpansion: "POV: You listed with a discount broker to save on commission... Now your home has been sitting for 90 days and you've dropped the price twice. Here's what went wrong.",
    isPremium: true,
  },
  {
    category: "seller",
    format: "social",
    hookText: "SOLD in 3 days for 8% over asking! Here's what we did differently:",
    useCase: "Success story showcase",
    exampleExpansion: "SOLD in 3 days for 8% over asking! Here's what we did differently: Professional staging, strategic pricing, and a marketing blitz that reached 50K+ buyers.",
    isPremium: false,
  },
  {
    category: "seller",
    format: "social",
    hookText: "Thinking about selling? Here's what homes in [Neighborhood] are actually selling for (not just listing for):",
    useCase: "Market reality check",
    exampleExpansion: "Thinking about selling? Here's what homes in Westlake are actually selling for (not just listing for): Average list price: $1.2M. Average sale price: $1.15M. Days on market: 45.",
    isPremium: false,
  },
  {
    category: "seller",
    format: "social",
    hookText: "Free home valuation? Sure. Accurate home valuation? That requires a conversation.",
    useCase: "Positioning expertise over algorithms",
    exampleExpansion: "Free home valuation? Sure. Accurate home valuation? That requires a conversation. Zillow says your home is worth $X. I can tell you what it will actually sell for and why.",
    isPremium: true,
  },
  {
    category: "seller",
    format: "email",
    hookText: "I have 3 buyers looking in your neighborhood right now...",
    useCase: "Creating FOMO for potential sellers",
    exampleExpansion: "I have 3 buyers looking in your neighborhood right now... All pre-approved, all motivated, and all frustrated by the lack of inventory. If you've been thinking about selling, now might be the time.",
    isPremium: true,
  },
  {
    category: "seller",
    format: "email",
    hookText: "Your home value just increased. Here's by how much:",
    useCase: "Market update to past clients",
    exampleExpansion: "Your home value just increased. Here's by how much: Based on recent sales in [Neighborhood], homes like yours have appreciated 12% in the last year. Curious what that means for you?",
    isPremium: true,
  },
  {
    category: "seller",
    format: "video",
    hookText: "I photographed 100+ homes this year. These are the ones that sold fastest:",
    useCase: "Presentation matters",
    exampleExpansion: "I photographed 100+ homes this year. These are the ones that sold fastest: Clean, bright, and staged. Here's exactly what we did to make them stand out.",
    isPremium: true,
  },
  {
    category: "seller",
    format: "video",
    hookText: "Should you sell now or wait? Here's how to decide:",
    useCase: "Timing guidance",
    exampleExpansion: "Should you sell now or wait? Here's how to decide: Look at these 4 factors - interest rates, local inventory, your equity position, and your personal timeline.",
    isPremium: true,
  },
  {
    category: "seller",
    format: "social",
    hookText: "Before you hire a photographer, do these 5 things to your home:",
    useCase: "Pre-listing prep",
    exampleExpansion: "Before you hire a photographer, do these 5 things to your home: Declutter, deep clean, fix minor repairs, add fresh flowers, and turn on all the lights. These small changes make a huge difference in photos.",
    isPremium: false,
  },
  {
    category: "seller",
    format: "social",
    hookText: "Pricing strategy: Why we listed at $X to sell at $Y",
    useCase: "Strategic pricing explanation",
    exampleExpansion: "Pricing strategy: Why we listed at $489K to sell at $505K. Strategic underpricing created urgency, attracted multiple buyers, and sparked a bidding war. Here's when this strategy works:",
    isPremium: true,
  },
  {
    category: "seller",
    format: "email",
    hookText: "It's time to talk about selling. Here's why:",
    useCase: "Market timing email",
    exampleExpansion: "It's time to talk about selling. Here's why: Inventory is low, buyer demand is high, and your home value has increased 15% since we last spoke. Let's schedule a call to discuss your options.",
    isPremium: true,
  },
  {
    category: "seller",
    format: "carousel",
    hookText: "The Ultimate Home Staging Checklist (Room by Room)",
    useCase: "Actionable staging guide",
    exampleExpansion: "Slide 1: The Ultimate Home Staging Checklist. Slide 2: Living Room - Declutter, depersonalize, add lighting. Slide 3: Kitchen - Clear counters, fresh flowers... (continues)",
    isPremium: false,
  },
  {
    category: "seller",
    format: "carousel",
    hookText: "Before & After: How Staging Transformed These Homes",
    useCase: "Visual staging impact",
    exampleExpansion: "Slide 1: Before & After: Staging Impact. Slide 2-3: Living room before/after. Slide 4-5: Kitchen before/after... (continues with multiple rooms)",
    isPremium: true,
  },

  // INVESTOR HOOKS
  {
    category: "investor",
    format: "video",
    hookText: "This property cash flows $2K/month. Here's the math:",
    useCase: "Investment property showcase",
    exampleExpansion: "This property cash flows $2K/month. Here's the math: Purchase price $350K, rent $3,200/mo, mortgage + expenses $1,200/mo = $2K positive cash flow.",
    isPremium: false,
  },
  {
    category: "investor",
    format: "video",
    hookText: "I just found a 1031 exchange opportunity that's perfect for...",
    useCase: "Tax strategy content",
    exampleExpansion: "I just found a 1031 exchange opportunity that's perfect for investors looking to defer capital gains. This 4-unit property in [Area] has a 9% cap rate.",
    isPremium: false,
  },
  {
    category: "investor",
    format: "video",
    hookText: "Real estate investors: Stop buying in [City]. Buy HERE instead.",
    useCase: "Emerging market opportunity",
    exampleExpansion: "Real estate investors: Stop buying in Austin. Buy in Round Rock instead. Same appreciation potential, 40% lower entry price, and better cash flow.",
    isPremium: true,
  },
  {
    category: "investor",
    format: "video",
    hookText: "This is what a 15% ROI looks like in real estate...",
    useCase: "ROI breakdown education",
    exampleExpansion: "This is what a 15% ROI looks like in real estate... Let me break down the numbers on this duplex that just hit the market.",
    isPremium: true,
  },
  {
    category: "investor",
    format: "social",
    hookText: "Off-market deal alert: 6-unit apartment building, 8.5% cap rate, needs work",
    useCase: "Deal flow showcase",
    exampleExpansion: "Off-market deal alert: 6-unit apartment building, 8.5% cap rate, needs work. Current owner is motivated. Serious investors only - DM for details.",
    isPremium: false,
  },
  {
    category: "investor",
    format: "social",
    hookText: "Appreciation vs Cash Flow: Which should you prioritize in 2024?",
    useCase: "Strategy discussion",
    exampleExpansion: "Appreciation vs Cash Flow: Which should you prioritize in 2024? The answer depends on your timeline, tax situation, and risk tolerance. Here's how to decide:",
    isPremium: true,
  },
  {
    category: "investor",
    format: "video",
    hookText: "Airbnb vs long-term rental: The numbers might surprise you",
    useCase: "Investment strategy comparison",
    exampleExpansion: "Airbnb vs long-term rental: The numbers might surprise you. I ran the math on the same property both ways. Here's what I found:",
    isPremium: true,
  },
  {
    category: "investor",
    format: "video",
    hookText: "How to find off-market deals (without spending money on lists)",
    useCase: "Deal sourcing strategies",
    exampleExpansion: "How to find off-market deals (without spending money on lists): These 5 free strategies helped me find 12 off-market properties last year.",
    isPremium: true,
  },
  {
    category: "investor",
    format: "social",
    hookText: "Just analyzed 50 rental properties in [City]. Here's what I found:",
    useCase: "Market research insights",
    exampleExpansion: "Just analyzed 50 rental properties in Austin. Here's what I found: Average cap rate 6.5%, best cash flow in suburbs, highest appreciation downtown. DM for the full report.",
    isPremium: true,
  },
  {
    category: "investor",
    format: "social",
    hookText: "House hacking: How to live for free (or close to it)",
    useCase: "Creative investment strategy",
    exampleExpansion: "House hacking: How to live for free (or close to it). Buy a duplex, live in one unit, rent the other. Your tenant pays your mortgage. Here's a real example:",
    isPremium: false,
  },
  {
    category: "investor",
    format: "email",
    hookText: "New investment opportunity: 8% cap rate, off-market, needs your decision by Friday",
    useCase: "Urgent deal alert",
    exampleExpansion: "New investment opportunity: 8% cap rate, off-market, needs your decision by Friday. This 4-plex in [Area] won't last. I've attached the full analysis. Call me if you're interested.",
    isPremium: true,
  },
  {
    category: "investor",
    format: "carousel",
    hookText: "How to Analyze a Rental Property in 5 Steps",
    useCase: "Investment education",
    exampleExpansion: "Slide 1: How to Analyze a Rental Property. Slide 2: Calculate potential rent. Slide 3: Estimate expenses. Slide 4: Determine cash flow... (continues)",
    isPremium: true,
  },
  {
    category: "investor",
    format: "carousel",
    hookText: "Real Estate Investment Strategies Explained",
    useCase: "Investment education",
    exampleExpansion: "Slide 1: Investment Strategies. Slide 2: Buy and hold. Slide 3: Fix and flip. Slide 4: BRRRR method. Slide 5: House hacking... (continues)",
    isPremium: true,
  },

  // LOCAL HOOKS
  {
    category: "local",
    format: "video",
    hookText: "5 things that surprised me when I moved to [City]",
    useCase: "Local insights for newcomers",
    exampleExpansion: "5 things that surprised me when I moved to Austin: The traffic (worse than expected), the food scene (better than expected), and 3 other things nobody tells you.",
    isPremium: false,
  },
  {
    category: "local",
    format: "video",
    hookText: "Hidden gem alert: This [City] neighborhood is about to blow up",
    useCase: "Emerging neighborhood spotlight",
    exampleExpansion: "Hidden gem alert: This Austin neighborhood is about to blow up. New HEB, Apple campus nearby, and home prices still under $400K. Here's what you need to know:",
    isPremium: false,
  },
  {
    category: "local",
    format: "video",
    hookText: "Best neighborhoods in [City] for families with kids (by school district)",
    useCase: "Family-focused local guide",
    exampleExpansion: "Best neighborhoods in Austin for families with kids (by school district): Let me break down the top 5 areas with great schools, parks, and family-friendly amenities.",
    isPremium: true,
  },
  {
    category: "local",
    format: "video",
    hookText: "Everyone's moving to [City]. Here's where they're actually buying:",
    useCase: "Migration trend analysis",
    exampleExpansion: "Everyone's moving to Austin. Here's where they're actually buying: Tech workers → Domain area, families → Round Rock, retirees → Lakeway. Let me explain why.",
    isPremium: true,
  },
  {
    category: "local",
    format: "social",
    hookText: "New to [City]? Here's your neighborhood cheat sheet:",
    useCase: "Relocation guide",
    exampleExpansion: "New to Austin? Here's your neighborhood cheat sheet: Downtown = walkability, Westlake = luxury, Mueller = community, Domain = modern. Which vibe fits you?",
    isPremium: false,
  },
  {
    category: "local",
    format: "social",
    hookText: "Just toured 12 homes in [Neighborhood] this week. Here's what I'm seeing:",
    useCase: "Real-time market insights",
    exampleExpansion: "Just toured 12 homes in Mueller this week. Here's what I'm seeing: Bidding wars are back, inventory is tight, and homes under $600K are going in 3 days.",
    isPremium: false,
  },
  {
    category: "local",
    format: "social",
    hookText: "Coffee shop test: The best neighborhoods in [City] all have THIS in common",
    useCase: "Lifestyle-based neighborhood analysis",
    exampleExpansion: "Coffee shop test: The best neighborhoods in Austin all have THIS in common - walkable local coffee shops. Here are my top 5 neighborhoods that pass the test:",
    isPremium: true,
  },
  {
    category: "local",
    format: "video",
    hookText: "The [City] neighborhoods that appreciated the most in the last 5 years",
    useCase: "Historical market analysis",
    exampleExpansion: "The Austin neighborhoods that appreciated the most in the last 5 years: Number 1 might surprise you. Here's the data and what it means for buyers today.",
    isPremium: true,
  },
  {
    category: "local",
    format: "video",
    hookText: "Best coffee shops in [City] by neighborhood (a realtor's guide)",
    useCase: "Lifestyle content",
    exampleExpansion: "Best coffee shops in Austin by neighborhood (a realtor's guide): Because where you get your morning coffee matters. Here are my favorites in each area.",
    isPremium: false,
  },
  {
    category: "local",
    format: "social",
    hookText: "Neighborhood comparison: [Area A] vs [Area B]",
    useCase: "Side-by-side comparison",
    exampleExpansion: "Neighborhood comparison: Mueller vs Domain. Mueller = community feel, parks, local shops. Domain = modern, walkable, restaurants. Both great, totally different vibes. Which fits you?",
    isPremium: false,
  },
  {
    category: "local",
    format: "social",
    hookText: "What $500K buys you in different [City] neighborhoods:",
    useCase: "Price comparison across areas",
    exampleExpansion: "What $500K buys you in different Austin neighborhoods: Downtown = 1-bed condo, Mueller = 3-bed townhome, Pflugerville = 4-bed house with yard. Location vs space - you choose.",
    isPremium: false,
  },
  {
    category: "local",
    format: "email",
    hookText: "Your [Neighborhood] market report: What happened in Q4",
    useCase: "Quarterly neighborhood update",
    exampleExpansion: "Your Mueller market report: What happened in Q4. Median sale price up 8%, days on market down to 25, and 3 new developments breaking ground. Here's what it means for your home value:",
    isPremium: true,
  },
  {
    category: "local",
    format: "carousel",
    hookText: "Neighborhood Spotlight: [Neighborhood Name]",
    useCase: "Deep dive into specific area",
    exampleExpansion: "Slide 1: Neighborhood Spotlight: Mueller. Slide 2: Location & Walkability. Slide 3: Schools & Parks. Slide 4: Home Prices & Trends... (continues)",
    isPremium: true,
  },
  {
    category: "local",
    format: "carousel",
    hookText: "A Day in [Neighborhood]: Local's Guide",
    useCase: "Lifestyle showcase",
    exampleExpansion: "Slide 1: A Day in Mueller. Slide 2: Morning coffee at Houndstooth. Slide 3: Farmers market. Slide 4: Lunch at Contigo... (continues with full day itinerary)",
    isPremium: false,
  },

  // LUXURY HOOKS
  {
    category: "luxury",
    format: "video",
    hookText: "Inside a $5M home that's been sitting for 6 months. Here's why it won't sell:",
    useCase: "Luxury market analysis",
    exampleExpansion: "Inside a $5M home that's been sitting for 6 months. Here's why it won't sell: Overpriced by $800K, dated finishes, and poor marketing. Let me show you what luxury buyers actually want.",
    isPremium: false,
  },
  {
    category: "luxury",
    format: "video",
    hookText: "What $3M actually gets you in [City] right now",
    useCase: "Luxury market snapshot",
    exampleExpansion: "What $3M actually gets you in Austin right now: Westlake estate with pool, downtown penthouse with views, or 10 acres in the hill country. Let me show you all three.",
    isPremium: false,
  },
  {
    category: "luxury",
    format: "video",
    hookText: "Luxury home buyers: Stop looking at price per square foot. Look at THIS instead.",
    useCase: "Luxury buyer education",
    exampleExpansion: "Luxury home buyers: Stop looking at price per square foot. Look at THIS instead. At this price point, it's all about location, views, and lifestyle. Here's how to evaluate luxury properties:",
    isPremium: true,
  },
  {
    category: "luxury",
    format: "video",
    hookText: "The difference between a $2M home and a $5M home isn't what you think",
    useCase: "Luxury market education",
    exampleExpansion: "The difference between a $2M home and a $5M home isn't what you think. It's not about size or finishes - it's about these 3 things that luxury buyers actually care about.",
    isPremium: true,
  },
  {
    category: "luxury",
    format: "social",
    hookText: "Just listed: Architectural masterpiece in [Neighborhood]. $4.2M. 48-hour private showing window.",
    useCase: "Exclusive listing announcement",
    exampleExpansion: "Just listed: Architectural masterpiece in Westlake. $4.2M. 48-hour private showing window. Serious buyers only - this won't last. DM for details.",
    isPremium: false,
  },
  {
    category: "luxury",
    format: "social",
    hookText: "Luxury isn't about the price tag. It's about the lifestyle.",
    useCase: "Lifestyle-focused luxury marketing",
    exampleExpansion: "Luxury isn't about the price tag. It's about the lifestyle. Private wine cellar, home theater, resort-style pool, and views for days. This is what $3.5M gets you in [Area].",
    isPremium: true,
  },
  {
    category: "luxury",
    format: "video",
    hookText: "Luxury home features that actually add value vs ones that don't",
    useCase: "Luxury renovation advice",
    exampleExpansion: "Luxury home features that actually add value vs ones that don't: That $100K pool? Adds $50K. That wine cellar? Adds $80K. Let me break down the ROI on luxury upgrades.",
    isPremium: true,
  },
  {
    category: "luxury",
    format: "video",
    hookText: "How to negotiate a luxury home purchase (it's different than regular homes)",
    useCase: "Luxury negotiation strategy",
    exampleExpansion: "How to negotiate a luxury home purchase (it's different than regular homes): At this price point, it's less about price and more about terms. Here's what luxury sellers actually care about.",
    isPremium: true,
  },
  {
    category: "luxury",
    format: "social",
    hookText: "Just previewed tomorrow's $6M listing. Here's a sneak peek:",
    useCase: "Exclusive preview teaser",
    exampleExpansion: "Just previewed tomorrow's $6M listing. Here's a sneak peek: Infinity pool overlooking the city, chef's kitchen, 1,000-bottle wine cellar, and a home theater that rivals the Alamo Drafthouse. Full listing drops tomorrow.",
    isPremium: true,
  },
  {
    category: "luxury",
    format: "social",
    hookText: "Luxury market update: What's selling and what's sitting in [Area]",
    useCase: "High-end market analysis",
    exampleExpansion: "Luxury market update: What's selling and what's sitting in Westlake. Homes under $3M = flying off the market. Homes over $5M = sitting 90+ days. Here's why:",
    isPremium: true,
  },
  {
    category: "luxury",
    format: "email",
    hookText: "Exclusive invitation: Private showing of [Address] before it hits the market",
    useCase: "VIP client engagement",
    exampleExpansion: "Exclusive invitation: Private showing of 123 Westlake Dr before it hits the market. This $4.5M estate is exactly what you've been looking for. Available for viewing this Thursday 2-4pm. Interested?",
    isPremium: true,
  },
  {
    category: "luxury",
    format: "carousel",
    hookText: "Inside [Address]: A $X Million Masterpiece",
    useCase: "Luxury listing showcase",
    exampleExpansion: "Slide 1: Inside 123 Westlake Dr: A $4.5M Masterpiece. Slide 2: Grand entrance. Slide 3: Chef's kitchen. Slide 4: Primary suite... (continues with property highlights)",
    isPremium: false,
  },
  {
    category: "luxury",
    format: "carousel",
    hookText: "Luxury Home Features That Define [City]'s High-End Market",
    useCase: "Luxury market trends",
    exampleExpansion: "Slide 1: Luxury Features in Austin. Slide 2: Infinity pools with views. Slide 3: Wine cellars. Slide 4: Smart home tech... (continues)",
    isPremium: true,
  },

  // RELOCATION HOOKS
  {
    category: "relocation",
    format: "video",
    hookText: "Thinking about moving to [City]? Here's what nobody tells you:",
    useCase: "Honest relocation guide",
    exampleExpansion: "Thinking about moving to Austin? Here's what nobody tells you: The good (food, weather, no state tax), the bad (traffic, heat, property taxes), and the surprising (culture shock for East Coasters).",
    isPremium: false,
  },
  {
    category: "relocation",
    format: "video",
    hookText: "I help people relocate to [City] for a living. These are the 5 questions I always get:",
    useCase: "FAQ-style relocation content",
    exampleExpansion: "I help people relocate to Austin for a living. These are the 5 questions I always get: Where should I live? How's the job market? What about schools? Let me answer all of them.",
    isPremium: false,
  },
  {
    category: "relocation",
    format: "video",
    hookText: "Moving from [State] to [State]? Here's what your money will get you:",
    useCase: "Cost of living comparison",
    exampleExpansion: "Moving from California to Texas? Here's what your money will get you: That $800K SF condo? It's a 4-bed house with a pool in Austin. Let me show you the difference.",
    isPremium: true,
  },
  {
    category: "relocation",
    format: "video",
    hookText: "Corporate relocation to [City]? I've helped 50+ families make the move. Here's my process:",
    useCase: "Corporate relocation services",
    exampleExpansion: "Corporate relocation to Austin? I've helped 50+ families make the move. Here's my process: Virtual tours, school research, neighborhood matching, and a seamless closing - all coordinated remotely.",
    isPremium: true,
  },
  {
    category: "relocation",
    format: "social",
    hookText: "Welcome to [City]! Here's your first-week survival guide:",
    useCase: "New resident welcome",
    exampleExpansion: "Welcome to Austin! Here's your first-week survival guide: Get your TX driver's license, find your favorite taco spot, learn to say 'y'all', and prepare for the heat. Need help finding a home? I've got you.",
    isPremium: false,
  },
  {
    category: "relocation",
    format: "social",
    hookText: "Just helped another family relocate from [State]. Here's where they landed and why:",
    useCase: "Relocation success story",
    exampleExpansion: "Just helped another family relocate from California. Here's where they landed and why: Round Rock for the schools, 4-bed house for $550K (would be $2M in SF), and 15-min commute to Apple campus.",
    isPremium: true,
  },
  {
    category: "relocation",
    format: "video",
    hookText: "Remote worker relocating to [City]? Here are the best neighborhoods for you:",
    useCase: "Remote worker relocation guide",
    exampleExpansion: "Remote worker relocating to Austin? Here are the best neighborhoods for you: Fast internet, coffee shops, co-working spaces, and community. Let me show you the top 5.",
    isPremium: true,
  },
  {
    category: "relocation",
    format: "video",
    hookText: "How to buy a home in [City] before you move (yes, it's possible)",
    useCase: "Remote buying process",
    exampleExpansion: "How to buy a home in Austin before you move (yes, it's possible): Virtual tours, remote closings, and local representation. Here's my step-by-step process.",
    isPremium: true,
  },
  {
    category: "relocation",
    format: "social",
    hookText: "[State] to [State] relocation guide: What to expect",
    useCase: "State-to-state comparison",
    exampleExpansion: "California to Texas relocation guide: What to expect. Lower cost of living, no state income tax, but higher property taxes and different culture. Here's the full breakdown:",
    isPremium: false,
  },
  {
    category: "relocation",
    format: "social",
    hookText: "Helping another tech worker relocate to [City] this month. Here's their wishlist:",
    useCase: "Relocation case study",
    exampleExpansion: "Helping another tech worker relocate to Austin this month. Here's their wishlist: Fast internet, walkable neighborhood, good schools, under $700K. Found them 3 perfect options in Round Rock.",
    isPremium: true,
  },
  {
    category: "relocation",
    format: "email",
    hookText: "Your [City] relocation packet is ready (schools, neighborhoods, and market data)",
    useCase: "Relocation resource delivery",
    exampleExpansion: "Your Austin relocation packet is ready (schools, neighborhoods, and market data). I've compiled everything you need to make an informed decision about where to live. Let's schedule a call to go through it together.",
    isPremium: true,
  },
  {
    category: "relocation",
    format: "carousel",
    hookText: "Moving to [City]? Your Complete Relocation Guide",
    useCase: "Comprehensive relocation resource",
    exampleExpansion: "Slide 1: Moving to Austin? Your Complete Guide. Slide 2: Cost of Living Comparison. Slide 3: Best Neighborhoods. Slide 4: Schools... (continues)",
    isPremium: true,
  },
  {
    category: "relocation",
    format: "carousel",
    hookText: "Cost of Living Comparison: [City A] vs [City B]",
    useCase: "Relocation decision tool",
    exampleExpansion: "Slide 1: SF vs Austin Cost Comparison. Slide 2: Housing costs. Slide 3: Taxes. Slide 4: Transportation. Slide 5: Overall savings... (continues)",
    isPremium: false,
  },

  // GENERAL HOOKS
  {
    category: "general",
    format: "video",
    hookText: "Real estate agents won't tell you this, but I will:",
    useCase: "Transparency/honesty positioning",
    exampleExpansion: "Real estate agents won't tell you this, but I will: Sometimes it's better to wait. Here's how to know if now is the right time for you to buy or sell.",
    isPremium: false,
  },
  {
    category: "general",
    format: "video",
    hookText: "I've been doing this for [X] years. This is the biggest mistake I see people make:",
    useCase: "Experience-based advice",
    exampleExpansion: "I've been doing this for 10 years. This is the biggest mistake I see people make: Letting emotions drive their decisions. Here's how to stay objective when buying or selling.",
    isPremium: false,
  },
  {
    category: "general",
    format: "video",
    hookText: "You're not crazy. The real estate market IS confusing right now. Let me explain:",
    useCase: "Market confusion clarification",
    exampleExpansion: "You're not crazy. The real estate market IS confusing right now. Let me explain: Rates are up, prices are up, but inventory is down. Here's what it all means for you.",
    isPremium: false,
  },
  {
    category: "general",
    format: "video",
    hookText: "POV: You're about to make the biggest financial decision of your life with zero training",
    useCase: "Positioning yourself as the guide",
    exampleExpansion: "POV: You're about to make the biggest financial decision of your life with zero training. That's where I come in. Here's how I help my clients navigate the process with confidence.",
    isPremium: true,
  },
  {
    category: "general",
    format: "social",
    hookText: "Client win of the week:",
    useCase: "Success story showcase",
    exampleExpansion: "Client win of the week: Helped first-time buyers get into their dream home with 3% down, beat out 2 other offers, and stayed under budget. This is why I love what I do.",
    isPremium: false,
  },
  {
    category: "general",
    format: "social",
    hookText: "Real estate tip of the day:",
    useCase: "Daily tip series",
    exampleExpansion: "Real estate tip of the day: Always get a pre-inspection before making an offer on an older home. It gives you negotiating power and prevents surprises. Trust me on this one.",
    isPremium: false,
  },
  {
    category: "general",
    format: "social",
    hookText: "Things I wish every buyer/seller knew before starting the process:",
    useCase: "Educational thread starter",
    exampleExpansion: "Things I wish every buyer/seller knew before starting the process: 1) It takes longer than you think, 2) Emotions will run high, 3) The right agent makes all the difference. Let me elaborate:",
    isPremium: true,
  },
  {
    category: "general",
    format: "video",
    hookText: "The real estate market is shifting. Here's what it means for you:",
    useCase: "Market shift explanation",
    exampleExpansion: "The real estate market is shifting. Here's what it means for you: Whether you're buying, selling, or investing, these changes will impact your strategy. Let me break it down.",
    isPremium: false,
  },
  {
    category: "general",
    format: "video",
    hookText: "Why I became a real estate agent (and why I'll never do anything else)",
    useCase: "Personal brand story",
    exampleExpansion: "Why I became a real estate agent (and why I'll never do anything else): It's not about the money or the flexibility. It's about helping people make the biggest decision of their lives with confidence.",
    isPremium: false,
  },
  {
    category: "general",
    format: "social",
    hookText: "Question of the day: What's your biggest fear about buying/selling a home?",
    useCase: "Engagement post",
    exampleExpansion: "Question of the day: What's your biggest fear about buying/selling a home? Drop it in the comments and I'll address the top 3 in my next post.",
    isPremium: false,
  },
  {
    category: "general",
    format: "social",
    hookText: "This week in real estate: [Market Update]",
    useCase: "Weekly market summary",
    exampleExpansion: "This week in real estate: Rates held steady at 6.8%, inventory increased 5%, and we saw the first bidding war in 3 months. Here's what it all means:",
    isPremium: false,
  },
  {
    category: "general",
    format: "email",
    hookText: "Happy anniversary! It's been [X] years since you bought your home.",
    useCase: "Client anniversary touchpoint",
    exampleExpansion: "Happy anniversary! It's been 3 years since you bought your home. Your home value has increased significantly since then. Curious what it's worth now? I'd be happy to run a current market analysis for you.",
    isPremium: false,
  },
  {
    category: "general",
    format: "carousel",
    hookText: "Real Estate Myths vs Reality",
    useCase: "Myth-busting educational content",
    exampleExpansion: "Slide 1: Real Estate Myths vs Reality. Slide 2: Myth: You need 20% down. Reality: Many programs offer 3-5% down. Slide 3: Myth: Spring is the only time to sell... (continues)",
    isPremium: false,
  },
  {
    category: "general",
    format: "carousel",
    hookText: "Real Estate Terms Every Buyer Should Know",
    useCase: "Glossary education",
    exampleExpansion: "Slide 1: Real Estate Terms. Slide 2: Escrow explained. Slide 3: Earnest money. Slide 4: Contingencies... (continues with 10 terms)",
    isPremium: false,
  },
];

async function seedHooks() {
  const connection = await createConnection(process.env.DATABASE_URL);
  
  console.log('🌱 Seeding hooks...');
  
  let inserted = 0;
  for (const hook of hookSeeds) {
    try {
      await connection.execute(
        'INSERT INTO hooks (category, format, hookText, useCase, exampleExpansion, isPremium) VALUES (?, ?, ?, ?, ?, ?)',
        [hook.category, hook.format, hook.hookText, hook.useCase, hook.exampleExpansion, hook.isPremium ? 1 : 0]
      );
      inserted++;
    } catch (error) {
      console.error(`Failed to insert hook: ${hook.hookText.substring(0, 50)}...`, error.message);
    }
  }
  
  await connection.end();
  
  console.log(`✅ Successfully seeded ${inserted} hooks!`);
}

seedHooks().catch(console.error);
